# Generated by Django 5.0.6 on 2024-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombreCompleto',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(max_length=10),
        ),
    ]
